# argo-workflows base values
controller:
  workflowNamespaces:
    - argo
server:
  extraArgs:
    - --auth-mode=server
  serviceAnnotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: argo-workflows
