title: Zingo Infrastructure
favicon: https://raw.githubusercontent.com/nicogaldamez/zcash-brand/main/zcash-icons/yellow/zcash-icon-yellow.png
headerStyle: boxed
layout:
  Golden (Mainnet):
    style: row
    columns: 3
    header: false
  Golden (Testnet):
    style: row
    columns: 3
    header: false
  Tryouts:
    style: row
    columns: 3
  Platform:
    style: row
    columns: 3
