---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webhook-signal-secrets
  namespace: monitoring
spec:
  encryptedData:
    signal.yaml: AgBRsaxVN3lW2yp8TqdfK38+XPlazpV3wAqqDYO8Tr/CJJO6ShGuISQ6ZnHIwdKEgKJ8TkCTShl/icGE4AJfyc90F0B4ovcFajrRstDqXbMSzK3Qn8Pdd6OrbPRZaZHZS4DYMt9yCfFAmabMWi5sOM9+Ax9BpEHuPDJxBPg4Crm+ozvEh+SmSVtxk/6Eqcl4aCXhhvP8nHEqsukXfo1tA9fABG3ZXeAfdHkSnbNXcVnt8zFaAPbImWB0iNUGhvY8ceT/qULc5TsiST145edKaipOqkqMWkkYfzuUC1uLKP4t2CBJ+I1KtgYo++CNWck3j2SSgofozt7qZLRYI7VRrBlUKpu51ru5uHgkcnKAH5ktitHbGDg6QWVEOxHhqFNPLKTVoNqPBlilY2oFPHOYnPL0rgArpLSHoRHun0AE8zkgjSEymv2qML2nkXoGwnwt7xJ/CpeoTyss3TJsA7XX8cNOJss0Xwbs4dRsJzODy8FgzHVQkIXOhisS6qaJ8CfBB+FsXUff9a5ekiNMIF9pCS2YhNPenRHrGtQZbECLu84NKoTUX7EW9cPSl8/xQnp+wi0NU1l1gPErhXK3yXSo6UdsCBZ91i5T8RR8d00CPOrcF4yqsADCZmMNc0tU7xSeUI2E3jtFPdAuUJsPd28IfOWeltXyVXqDZUxBiMBt1LWtkuPo9nWghLoh1sGkpQN6f3HcKMWrRih1RoXSkferDBLnIkrp7f2FTiAzIQlXsBBmJ7fhyrgl8U2LiHMwzGbn0QhKcZnsrugg5qmg2x4W6CtCus+/QRzAN4vh8LBHjLUymdAXiF6xQGwIhAYIE29AKIr03fcVZi85inevgc8N8Zq6oHMMUGq4/OE2pbNfYVTGxGtrlFpCXOba0FOYjFO9V9RGvXmmrkm/+ARBtXU4ALsp7fbDF9/BmGF/gvcRPrPtsw==
  template:
    metadata:
      name: webhook-signal-secrets
      namespace: monitoring
