apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webhook-signal-config
  namespace: monitoring
spec:
  encryptedData:
    config.yaml: AgAPQRLgRJNS11Rf0Oj1md2xlotENmgo3j5M1vN3cvarAiDTul8jCSBPqsQa9qGkF1/pXWTBc3O8CRdwd7r6dL0T3HWMRyvAfZl1LKZs1sI7+0qmPNUy/dpDT/lZ9baDllXrwCv80+KaHHdvBdRvCo9i3SrtgcCUx7/P2lSyvkG2rZkxAz4X/iBKzxNjYF8i5VNUQ3sg00GrqGm0J2eDBwN1SWWkzJrI5GyZ+2sOiW8t9sFPUxYn3Mly4LonHxO1j5FwOZ4iy+pnfSab7Xf4RfKGNzoM2/VzCXkLCaSPJrHNP68fJUInWkbsSMUJmrMygWL550yhrmuCD/mPH3nVht+pQ7k8T90I6DCGZaJ6lYNZgXdEXLQEzaiG3gaQhdT0/3fDHZt/EiCjo2xenblhq6dypudNu6aKNS4gs0lu9h9KKxpsFa6ukdWWjUozbwuVyubNSm272kdvC+mlSk16q2unH6obUuOvrBid+8tDPiBlvpzQ5C02eCmYefnUhrBRHFp4qYkA1uMKo5Bb3DJktHDiksOi1sQa86J83Tz+l8T48ji7K0UBAYn9E0L+aerfSXBxcPfEuDZ9SwSnjpSYZu+8WmgGc2jnrOofjyd/dNHzSpLcs98+pp3S4n1rt3uF987lDbPw9/8fbjexqX5szDkafyx5hQHumHgfb8sy3RNPa8+saBlKuO+mqBs7jgVhFudRFBbiWtH+5l64XfqwmJJyKpTCOwsnRrcvyCxHFLaWzxGXo4yMfSlS/MdPjJAPKxawZ6pEGn5V0zGHyhFpR6NAmIWXcTuOtjFo9ubtUos2pE2vUGXX8UwwUyaVse6OVCCgLAQ3OMqjB68CztXv9kmIzelGGbM0vzFOSXqNvce9XXYsNVd79kKac7uSCDMWnNbqUTuHIsXWO8mYtLpjvn0ouSt9jJrgLzHkO9oFSdX8A4clCZVA3vTgRsPVd+full3peh+sO8qkRscyaaaDXHp/pgpIL8kWlJFuhnRfwhL0y+NaaPJQAtGgG0rBvA==
  template:
    metadata:
      name: webhook-signal-config
      namespace: monitoring
