apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zaino-stable-mainnet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zingolabs/devops
    path: apps/zaino/stable-mainnet
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: zaino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zaino-stable-testnet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zingolabs/devops
    path: apps/zaino/stable-testnet
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: zaino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
