apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

helmCharts:
  - name: homepage
    repo: https://jameswynn.github.io/helm-charts
    version: 2.1.0
    releaseName: homepage
    namespace: homepage
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - target:
      kind: Service
      name: homepage
    patch: |
      - op: add
        path: /metadata/annotations/tailscale.com~1expose
        value: "true"
