apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

helmCharts:
  - name: homepage
    repo: https://jameswynn.github.io/helm-charts
    version: 2.1.0
    releaseName: homepage
    namespace: homepage
    includeCRDs: true
    valuesFile: values.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: homepage
    behavior: replace
    files:
      - settings.yaml=config/settings.yaml
      - services.yaml=config/services.yaml
      - widgets.yaml=config/widgets.yaml
      - kubernetes.yaml=config/kubernetes.yaml
    options:
      labels:
        app.kubernetes.io/name: homepage
        app.kubernetes.io/instance: homepage

patches:
  - target:
      kind: Service
      name: homepage
    patch: |
      - op: add
        path: /metadata/annotations/tailscale.com~1expose
        value: "true"
      - op: add
        path: /metadata/annotations/tailscale.com~1hostname
        value: "zingo-infra"
      - op: replace
        path: /spec/ports/0/port
        value: 80
