image:
  repository: ghcr.io/gethomepage/homepage
  tag: v1.11.0

enableRbac: true
serviceAccount:
  create: true

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "zingo-infra.vaquita-altair.ts.net"

# Config files are patched via kustomize configmap overlay
# See: settings.yaml, services.yaml, widgets.yaml
config: {}
