{{- if not .Values.authkey.existingSecret }}
{{- if not .Values.authkey.value }}
{{- fail "grpc-funnel: set either authkey.value or authkey.existingSecret" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grpc-funnel.fullname" . }}-authkey
  labels:
    {{- include "grpc-funnel.labels" . | nindent 4 }}
type: Opaque
stringData:
  TS_AUTHKEY: {{ .Values.authkey.value | quote }}
{{- end }}
