apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - sealed-authentik-secrets.yaml

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    version: 2026.5.3
    releaseName: authentik
    namespace: authentik
    valuesFile: values.yaml
